### ISSUE TITLE
[Feature request] Use FLORIS for AMR-Wind standin

### ISSUE THREAD

**Issue by misi9170** [NREL/hercules#62]
The current AMR-Wind stand-in does not contain any realistic physics. This feature (discussed with @paulf81 and @genevievestarke ) would use FLORIS (which contains steady-state physics) instead, so would account for wake interactions, albeit in an instantaneous way. 

Wind farm information would be read in from the amrwind.inp file, and a matching FLORIS model instantiated to be called timestep by timestep.

**Comment by paulf81** [comment]
Agree completely with this

**Comment by misi9170** [comment]
Closed by #63
