### ISSUE TITLE
Provide external driving signals to various py_sims

### ISSUE THREAD

**Issue by misi9170** [NREL/hercules#82]
FlorisStandin, PySAM, etc could be driven by external weather signals, for example:
- wind speed
- wind direction
- solar irradiance (multiple channels)
- temperature
- humidity

as well as grid signals, for example:
- load profile
- electricity price

These should be read in to the Hercules simulator as `external_signals`, similar to the way that the `"wind_power_reference"` is read in the WHOC example wind_farm_power_tracking_florisstandin [here](https://github.com/NREL/wind-hybrid-open-controller/pull/29).

Ideally, each signals will have it's own time column, so that different signal resolutions may be passed.
Also, each pysim will need to be updated to accept the `external_signals`

**Comment by genevievestarke** [comment]
@misi9170 We can close this issue, right? I think this has been addressed
